### ISSUE TITLE
Test less tested features

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#952]
Legacy:
- [x] Legacy instances should still start - they do.
- [x] It is no longer required that they be editable (no more adding/removing jar mods) - still works just fine.

FTB:
- [x] Installing an old version of a pack (legacy MC version < 1.6) and upgrading it to a newer version (MC >= 1.6) - this is FIXED in unstable.
- [ ] Adding custom patches will look for libraries in FTB's folder structure and won't download the missing libraries - split off into #967

Customized Minecraft version patches converted from {custom,version}.json:
- [x] autoupgrades of patch files (version.json and custom.json)
- [x] Change version of the patch should remove the customized patch from the patches folder
- [ ]  Minecraft version should be extracted from version patch when the patch is custom (let's have a generic function that allows querying version by uid and use that everywhere) - split off into #966

Last minute fixes:
- [x] Include SSL cert, see #960

**Comment by peterix** [comment]
Conversion of {version,custom}.json to patches needs work.

**Comment by TheDoctorsLife** [comment]
FTB works don't see any issues with it so far.

**Comment by peterix** [comment]
Now the version tab needs an 'edit'/'customize' button and a 'revert to default' button, where applicable.

**Comment by peterix** [comment]
FTB testing should include installing an old version of a pack (legacy MC version < 1.6) and upgrading it to a newer version (MC >= 1.6)

**Comment by peterix** [comment]
Autoupgrades are now DONE.

**Comment by peterix** [comment]
FTB is as derpy as ever.

- [ ] Adding custom patches will look for libraries in FTB's folder structure and won't download the missing libraries.

**Comment by peterix** [comment]
- [ ]  Minecraft version should be extracted from version patch when the patch is custom (let's have a generic function that allows querying version by uid and use that everywhere)

**Comment by peterix** [comment]
- [ ] Update help for dialog pages
- [ ] Update the site
